steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/tomolink-poc', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tomolink-poc']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'tomolink-poc', '--image', 'gcr.io/$PROJECT_ID/tomolink-poc', '--region', 'asia-northeast1','--platform', 'managed', '--quiet']
images:
- gcr.io/$PROJECT_ID/tomolink-poc
